version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    image: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:14-alpine
    volumes:
      - ./db/stats:/var/lib/postgresql/data
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 5

  ewm-service:
    build: ./ewm
    container_name: ewm-server
    image: ewm-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      ewm-db:
        condition: service_healthy

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - ./db/ewm:/var/lib/postgresql/data
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 5
